server:
  port: 8080
#数据库驱动配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tt?useSSL=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
# mybatis配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志配置
logging:
  level:
    root: info
    com.neu.t1: debug

# jwt配置
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头


